# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20161029_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_id', models.IntegerField(unique=True)),
                ('dimension', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('dim_name', models.CharField(max_length=50)),
                ('parent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_1', models.CharField(max_length=50)),
                ('dim_2', models.CharField(max_length=50)),
                ('dim_3', models.CharField(max_length=50)),
                ('attr_1', models.CharField(max_length=50)),
                ('attr_2', models.CharField(max_length=50)),
                ('attr_3', models.CharField(max_length=50)),
                ('date_associated', models.DateField()),
                ('numerator', models.IntegerField()),
                ('denominator', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_status', models.IntegerField()),
                ('loaded_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_id', models.IntegerField(unique=True)),
                ('metric_name', models.CharField(max_length=50)),
                ('metric_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_status', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='metricdata',
            name='metric_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Metrics'),
        ),
    ]
