# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20161105_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricdata',
            name='dim_2',
        ),
        migrations.RemoveField(
            model_name='metricdata',
            name='dim_3',
        ),
        migrations.AlterField(
            model_name='metricdata',
            name='dim_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Dimension'),
        ),
    ]
