# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-05 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20161105_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricdata',
            name='row_status',
            field=models.IntegerField(default=True),
        ),
    ]
