# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-06 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_auto_20161105_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimension',
            old_name='dimension',
            new_name='dim',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='dimension',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='rango.Dimension'),
            preserve_default=False,
        ),
    ]
