# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-06 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20161106_0451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimension',
            old_name='dim',
            new_name='dim_type',
        ),
    ]
