# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-06 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_auto_20161106_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rango.Dimension'),
        ),
    ]
