# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-09 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(upload_to='/home/sahil/django/KPI/media'),
        ),
    ]
